### ISSUE TITLE
React Native WebView Interaction

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Mobile#1]
## Overview
 Because WASM not work on react-native we will use and webview like runner for mobile app and interact with it via message passing

## Todo:
- [x] Use message passing from `@polkadot` or `@subwallet`/extension
- [x] Use fallback for some features like chome.storage, chrome.extension....
- [x] Check run in background (react native not run in background)
