### ISSUE TITLE
In-app Browser

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Mobile#18]
# Overview
In-app Browser is a simple browser with Substrate and EVM Provider and allows DApp interaction like on Mobile via extension.
We prepare to create this browser with `react-native-browser` with some simple UI.
From common mobile browsers, We can connect SubWallet Mobile with deep-link.

# Concept
## User Flow
```mermaid
graph TD
    FMB(From mobile browsers like Chrome/Safari/Firefox...)
    FSWA(From SubWallet App)
    FMB --Deep link--> OSWMB(Open DApp on SubWallet Mobile Browser)
    FSWA --> OSWMB
    OSWMB --> ODA(Open DApp with Injected Substrate/EVM provider)
```
## DApp - WebRunner interaction
```mermaid
sequenceDiagram
    DApp->>+Wallet Provider: Perform method
    Wallet Provider->>+SubWalletMobile: Send request (origin, tabId)
    SubWalletMobile->>+WebRunner: Forward request (origin, tabId)
    WebRunner->>-SubWalletMobile: Response request (origin, tabId)
    SubWalletMobile->>-Wallet Provider: Forward response (origin, tabId)
    Wallet Provider->>-DApp: Async resolve/reject
```

## Stage 1: Research (2022-08-24)
- [x] Interaction flow
- [x] Mobile App Browser
- [x] Deep link
- [x] Test Implementation
  - [x] Simple Mobile App Browser: input address, back, forward, reload...
  - [x] Make sure that interaction like web-runner is ok
  - [x] Test to inject EVM provider with name `window.ethereum` on Moonbeams app

## Stage 2: Basic Implementation  (2022-09-10)
- [x] Open application with deep-link
- [x] Inject Substrate Provider
- [x] Inject EVM Provider
- [x] Block Phishing site
- [x] Website Access (in #13)
- [x] Implement browser UI/UX
- [x] Confirmation popups
  - [x] Redux store for confirmation popup
  - [x] Create hook for handle all confirmation types
  - [x] Confirmation base screen
  - [x] Confirmation specify screen
    - [x] Authorizations
    - [x] Import Metadata
    - [x] Sign substrate transaction
    - [x] Send EVM transaction
    - [x] Sign EVM transaction
- [x] WebRunner Issues:
  - [x] Need API (message) to unsubcribe existed  handler in webrunner
## Stage 3: Full Implementation
- Deep-link: subwallet:// and link.subwallet.app://
  - [x] Deep link after intalls app
  - Register deep-link with app-store & play store to make sure that link to install the repository (Implement in #106)
- #107 
- [x] Advance features for mobile browser
  - [x] Predefined Dapps
  - [x] Bookmark and favorites
  - [x] Multi-tab interactions
