### ISSUE TITLE
Mobile - Update the latest web-runner (v1.3.12)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Mobile#1878]
**Describe the task**
Update the latest web-runner (v1.3.12)

**Comment by Quangdm-cdm** [comment]
- [ ]  Mobile - Support ERC-1155 #1872 
- [ ] Mobile - Support importing assets on Asset Hub #1871 
- [ ] Mobile - Support swap TAO on SimpleSwap #1877
- [ ] Mobile - Allow Polkadot namespace use EVM address via WalletConnect #1874 
- [ ] Mobile - Update validating recipient balance when sending Substrate token #1875 
- [ ] Mobile - Some updates related to the content of the Earning feature #1876
- [ ] Research improve notification for mobile
- [ ] Mobile - Support Avail Bridge #1870
- [ ] Mobile - Support Unified bridge on Polygon #1873
